#
# Module manifest for module 'SelectADOu'
#
# Generated by: Johannes Schöpp
#
# Generated on: 05.10.2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'SelectADOU.psm1'

    # Version number of this module.
    ModuleVersion        = '0.0.4'

    # Supported PSEditions
    CompatiblePSEditions = @("Desktop")

    # ID used to uniquely identify this module
    GUID                 = '05e43aef-12e2-421f-b0b0-8c05492ee542'

    # Author of this module
    Author               = 'Johannes Schöpp'

    # Company or vendor of this module
    CompanyName          = 'Johann Wolfgang Goethe-Universität Frankfurt'

    # Copyright statement for this module
    Copyright            = '2021'

    # Description of the functionality provided by this module
    Description          = 'A graphical selection tool of AD Organisational Units'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @(
        "ActiveDirectory"
    )

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies   = @(
        "PresentationFramework"
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        "Select-ADOU"
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                       = @(
                "ActiveDirectoy",
                "AD",
                "GUI"
            )

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # External dependent modules of this module
            ExternalModuleDependencies = @(
                "ActiveDirectory"
            )

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

